[managers.pacman]
add = "pacman -S #:?"
remove = "pacman -Rns #:?"
sudo = true
priority = 0

[hooks.once.install_paru]
priority = 5
command = """
git clone https://aur.archlinux.org/paru.git ~/paru/
cd ~/paru
makepkg -si
"""

[managers.paru]
add = "paru -S #:?"
remove = "paru -Rns #:?"
update = "paru"
priority = 10

[managers.cargo]
add = "cargo install #:?"
remove = "cargo uninstall #:?"
update = "cargo install #:?"
priority = 20

[packages]
pacman = ["git", "base-devel"]
paru = ["neovim", "fish", "rustup", "github-cli"]
cargo = ["cargo-nextest"]

[hooks.once]
set_rust_toolchain = {command="rustup default nightly", priority=15}
set_shell = "chsh -s /usr/bin/fish"
auth_github = "gh auth login --hostname github.com --git-protocol https"
git_name = "git config --global user.name vivax"
git_email = "git config --global user.email vivax3794@protonmail.com"

[hooks.update]
rust = {command="rustup update", priority=18}
