[module]
import = [
	"dotty_modules/system_packages.toml",
    "dotty_modules/de.toml",
    "dotty_modules/widgets.toml",
    "dotty_modules/audio.toml",
	"dotty_modules/git.toml",
	"dotty_modules/fish.toml",
	"dotty_modules/nvim.toml",
	"dotty_modules/rust.toml",
	"dotty_modules/discord.toml",
	"dotty_modules/tasks.toml",
]

[packages]
paru = [
	"kitty",
	"btop",
    "nvtop",
    "floorp",
    "steam",
    "obs-studio",
    "neofetch"
]

[files]
"~/.config/kitty/kitty.conf" = "./dotfiles/kitty.conf"

[template.abbr]
da = "dotty apply"
co = "cd ~/coding"
cc = "cd ~/dotty_config"

[template.alias]
dotty = "$HOME/coding/dotty/target/release/dotty"
