[module]
import = [
	"dotty_modules/system_packages.toml",
    "dotty_modules/hyprland.toml",
    "dotty_modules/niri.toml",
    "dotty_modules/widgets.toml",
    "dotty_modules/audio.toml",
	"dotty_modules/git.toml",
	"dotty_modules/fish.toml", "dotty_modules/nvim.toml", "dotty_modules/rust.toml",
	"dotty_modules/discord.toml",
	"dotty_modules/tasks.toml",
	"dotty_modules/game_dev.toml",
	"dotty_modules/ai.toml",
	"dotty_modules/web_dev.toml",
]

[packages]
paru = [
	"kitty",
	"btop",
    "zen-browser",
    "lutris",
    "umu-launcher",
    "steam",
    "obs-studio",
    "neofetch",
    "7zip",
    "winetricks",
    "protontricks",
    "man",
    "tree",
    "watchexec",
    "gamemode",
    "lib32-gamemode",
    "dolphin-emu",
    "qbittorrent",
    "testdisk",
    "extundelete",
    "zsa-keymapp",
    "firefox",
    "inkscape",
    "nbfc",
    "openssh",
    "whois",
    "earthly",
    "podman",
    "fastfetch",
    "v4l2loopback-dkms",
    "linux-headers",
    "downgrade"
]
cargo = ["tree-sitter-cli"]

[files]
"~/.config/kitty/kitty.conf" = "./dotfiles/kitty.conf"

[template.abbr]
da = "dotty apply"
