[module]
import = [
	"dotty_modules/system_packages.toml",
	"dotty_modules/git.toml",
	"dotty_modules/rust.toml",
]

[packages]
paru = ["neovim", "fish"]

[hooks.once]
set_shell = "chsh -s /usr/bin/fish"
