[managers.paru]
add = "paru -S #:?"
remove = "paru -Rns #:?"
update = "paru"
sudo = false
seperator = " "
priority = 10

[managers.cargo]
add = "cargo install #:?"
remove = "cargo uninstall #:?"
update = "cargo install #:?"
sudo = false
seperator = " "
priority = 20

[managers.pacman]
add = "pacman -S #:?"
remove = "pacman -Rns #:?"
sudo = true
seperator = " "
priority = 0

[packages]
cargo = ["cargo-nextest", "bacon"]
pacman = ["git", "base-devel"]
paru = ["neovim", "fish", "rustup", "github-cli"]

[dotty]

[hooks.once]
auth_github = "gh auth login --hostname github.com --git-protocol https"
git_email = "git config --global user.email vivax3794@protonmail.com"
set_shell = "chsh -s /usr/bin/fish"
git_name = "git config --global user.name vivax"

[hooks.once.install_paru]
command = """
git clone https://aur.archlinux.org/paru.git ~/paru/
cd ~/paru
makepkg -si
"""
priority = 5

[hooks.once.set_rust_toolchain]
command = "rustup default nightly"
priority = 15
