[packages]
paru = [
	"pipewire",
	"pipewire-audio",
	"pipewire-pulse",
	"pipewire-alsa",
	"pavucontrol",
	"wireplumber",
	"bluez",
	"bluez-utils"
]
service = ["bluetooth.service"]

[files]
"~/.config/wireplumber/wireplumber.conf.d/overwride.conf" = "./dotfiles/wireplumber.conf"

[template.abbr]
bc = "bluetoothctl connect AC:80:0A:F4:0B:FC"
bd = "bluetoothctl disconnect AC:80:0A:F4:0B:FC"
