[packages]
paru = [
	"nvidia",
	"nvidia-utils",
	"egl-wayland",
	"wayland",
    "wl-clipboard",
	"hyprland",
	"ttf-firacode-nerd",
    "noto-fonts-emoji",
    "dunst", # notifications
    "qt6-wayland",
    "xdg-desktop-portal",
    "xdg-desktop-portal-hyprland",
    "grim",
    "slurp",
    "tofi-git",
    "waybar",
    "pyprland",
    "hyprshot",
    "lib32-nvidia-utils",
    "nvidia-settings",
    "vulkan-icd-loader",
    "lib32-vulkan-icd-loader",
    "mpvpaper",
    "qt5-wayland"
]

[files."~/.config/hypr/hyprland.conf"]
source = "./dotfiles/hyprland.conf.tera"
post_hook = "hyprctl reload"

[files."~/.config/hypr/pyprland.toml"]
source = "./dotfiles/pyprland.toml"
post_hook = "pypr reload"

[files]
"~/.config/dunst/dunstrc"= "./dotfiles/dunstrc.ini"
"~/.config/tofi/config" = "./dotfiles/tofi"

[files."~/.config/waybar"]
source = "./dotfiles/waybar"
post_hook = "killall waybar; sleep 0.2; hyprctl dispatch exec waybar"

[files."/etc/systemd/system/getty@tty1.service.d/override.conf"]
source = "./dotfiles/getty.service"
sudo = true

[template]
startup = [
   "waybar",
    "pypr",
    "xrandr --output DP-1 --primary", # XWayland programs (mostly games) need this to launch on correct monitor
    "curl -X POST http://pi.home:1880/pc_on",
    "bash ~/dotty_config/scripts/wallpaper.sh"
]
