[packages]
paru = ["fish", "starship", "bat", "ripgrep", "exa", "zoxide"]

[files]
"~/.config/fish/config.fish" = "./dotfiles/config.fish.tera"
"~/.config/starship.toml" = "./dotfiles/starship.toml"

[hooks.once]
set_shell = "chsh -s /usr/bin/fish"

[template.abbr]
ls = "exa -la"
size = "exa -la --total-size"
grep = "rg"
cat = "bat"
cp = "cp -rv"
rm = "rm -rv"
mv = "mv -v"
cd = "z"
