[packages]
paru = ["libresprite", "blender", "unityhub", "lld", "clang", "mold", "ldtk", "binaryen", "wasm-bindgen"]
rust_component = ["rustc-codegen-cranelift-preview"]
rust_target = ["wasm32-unknown-unknown"]
