[packages]
paru = ["github-cli", "lazygit", "jujutsu"]

[hooks.once]
git_name = "git config --global user.name vivax"
git_email = "git config --global user.email vivax3794@protonmail.com"

[template.abbr]
backup = 'git add .; git commit -m "$(date)"; git push'
ghr = "gh repo create"
clone = "gh repo clone -- --depth 1"
gp = "git pull"
g = "lazygit"
