[packages]
paru = ["github-cli"]

[hooks.once]
auth_github = "gh auth login --hostname github.com --git-protocol https"
git_name = "git config --global user.name vivax"
git_email = "git config --global user.email vivax3794@protonmail.com"
