[packages]
paru = ["neovim", "python-pynvim"]

[files."~/.config/nvim"]
source = "./dotfiles/nvim"
post_hook = "nvim --headless '+Lazy! install' +qa"

[hooks.update]
nvim = "nvim --headless '+Lazy! update' +qa"
tree_sitter = "nvim --headless 'TSUpdate' +qa"

[template.abbr]
n = "nvim"
