[packages]
paru = ["rustup", "just", "hyperfine", "perf", "lld", "clang", "mold", "binaryen", "wasm-bindgen"]
cargo = [
    "cargo-nextest", 
    "bacon", 
    "wasm-pack", 
    "cargo-audit",
    "twiggy",
    "cargo-bloat",
    "mdbook",
    "cargo-mommy",
    "cargo-hack",
    "cargo-expand",
    "cargo-outdated",
    "typos-cli",
    "mdbook-callouts",
    "mdbookkit",
    "cargo-binstall", 
    "cargo-update",
    "cargo-edit"
]
rust_component = ["rust-analyzer", "rustc-codegen-cranelift-preview"]
rust_target = ["wasm32-unknown-unknown"]

[managers.cargo]
add = "cargo binstall -y #:?"
remove = "cargo uninstall #:?"
update = "cargo install-update -a"
priority = 20

[managers.rust_component]
add = "rustup component add #:?"
remove = "rustup component remove #:?"
priority = 17

[managers.rust_target]
add = "rustup target install #:?"
remove = "rustup target uninstall #:?"
priority = 16

[hooks.once]
set_rust_toolchain = {command="rustup default nightly", priority=15}
install_dagger = "curl -fsSL https://dl.dagger.io/dagger/install.sh | DAGGER_COMMIT=head BIN_DIR=$HOME/.local/bin sh"

[hooks.update]
update_dagger = "curl -fsSL https://dl.dagger.io/dagger/install.sh | DAGGER_COMMIT=head BIN_DIR=$HOME/.local/bin sh"
rust = {command="rustup update", priority=18}

[template.abbr]
c = "cargo"
cn = "cargo new"
cr = "cargo run"
ct = "cargo nextest run"
b = "bacon --job clippy-all --all-features"
j = "just"
t = "watchexec typos"
tw = "typos -w"

[template.alias]
just = "CARGO_MOMMYS_MOODS='chill/ominous/thirsty' CARGO_MOMMYS_ACTUAL=just cargo-mommy"

[files]
"~/.config/bacon/prefs.toml" = "./dotfiles/bacon.toml"

[template]
path_env = [
    "$HOME/.cargo/bin"
]
