[packages]
paru = ["rustup"]
cargo = ["cargo-nextest", "bacon"]
rust_component = ["rust-analyzer"]

[managers.cargo]
add = "cargo install #:?"
remove = "cargo uninstall #:?"
update = "cargo install #:?"
priority = 20

[managers.rust_component]
add = "rustup component add #:?"
remove = "rustup component remove #:?"
priority = 17

[hooks.once]
set_rust_toolchain = {command="rustup default nightly", priority=15}

[hooks.update]
rust = {command="rustup update", priority=18}

[template.abbr]
c = "cargo"
cn = "cargo new"
cr = "cargo run"
ct = "cargo nextest run"
b = "bacon"

[template]
path_env = [
    "$HOME/.cargo/bin",
    "$HOME/.rustup/toolchains/(rustup show active-toolchain | cut -d' ' -f1)/bin "
]
