[packages]
paru = ["rustup", "just", "hyperfine", "perf", "lld", "clang", "mold", "binaryen", "wasm-bindgen"]
cargo = ["cargo-nextest", "bacon", "flamegraph", "cargo-criterion", "cargo-pgo", "trunk", "wasm-pack", "cargo-audit", "twiggy", "wasm-snip", "cargo-bloat", "mdbook", "cargo-llvm-lines", "cargo-mommy", "cargo-hack", "cargo-llvm-cov", "cargo-mutants", "cargo-expand", "cargo-outdated", "cargo-msrv"]
rust_component = ["rust-analyzer", "llvm-tools-preview", "rustc-codegen-cranelift-preview"]
rust_target = ["wasm32-unknown-unknown"]

[managers.cargo]
add = "cargo install #:?"
remove = "cargo uninstall #:?"
update = "cargo install #:?"
priority = 20

[managers.rust_component]
add = "rustup component add #:?"
remove = "rustup component remove #:?"
priority = 17

[managers.rust_target]
add = "rustup target install #:?"
remove = "rustup target uninstall #:?"
priority = 16

[hooks.once]
set_rust_toolchain = {command="rustup default nightly", priority=15}

[hooks.update]
rust = {command="rustup update", priority=18}

[template.abbr]
c = "cargo"
cn = "cargo new"
cr = "cargo run"
ct = "cargo nextest run"
b = "bacon --job clippy-all --all-features --summary"
j = "just"

[template.alias]
just = "CARGO_MOMMYS_MOODS='chill/ominous/thirsty' CARGO_MOMMYS_ACTUAL=just cargo-mommy"

[template]
path_env = [
    "$HOME/.cargo/bin"
]
