[managers.pacman]
add = "pacman -S #:?"
remove = "pacman -Rns #:? || true"
sudo = true
priority = 0

[packages]
pacman = ["git", "base-devel"]

[hooks.once.install_paru]
priority = 5
command = """
git clone https://aur.archlinux.org/paru.git ~/paru/
cd ~/paru
makepkg -si
"""

[managers.paru]
add = "paru -S #:?"
remove = "paru -Rns $(for pkg in #:?; do pacman -Q \"$pkg\" &>/dev/null && echo \"$pkg\"; done) || true"
update = "paru"
priority = 10

[managers.service]
add = "systemctl enable #:?"
remove = "systemctl disable #:?"
priority = 100
