[packages]
fisher = ["jorgebucaran/nvm.fish"]
node = ["23"]
npm = ["@vue/language-server", "@vue/typescript-plugin", "vue-tsc", "typescript-language-server", "prettier", "serve"]
paru = [
  "webkit2gtk-4.1",
  "base-devel",
  "curl",
  "wget",
  "file",
  "openssl",
  "appmenu-gtk-module",
  "libappindicator-gtk3",
  "librsvg",
  "caddy",
]

[managers.node]
add = "fish -c 'nvm install #:?'"
remove = "fish -c 'nvm uninstall #:?' || true"

[managers.npm]
add = "fish -c 'nvm use v23.7.0 && npm -g install #:?' || true"
remove = "fish -c 'nvm use v23.7.0 && npm -g uninstall #:?' || true"
update = "fish -c 'nvm use v23.7.0 && npm update -g'"
priority = 60

[template.abbr]
node = "nvm use v23.7.0" 
